FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install -y tesseract-ocr postgresql-client
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN python3 -m pip install --upgrade pip
RUN pip3 install -r requirements.txt
COPY . /code
EXPOSE 8000
CMD ["sh", "./start_server.sh"]