# Generated by Django 3.2.23 on 2025-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalcompanyinfo',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
