# Generated by Django 3.2.23 on 2025-09-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250918_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_us',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalcompanyinfo',
            name='about_us',
            field=models.TextField(default=''),
        ),
    ]
