# Generated by Django 3.2.23 on 2025-09-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250918_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='historicalcompanyinfo',
            name='about_us',
        ),
    ]
